name: fraud-ieee-cis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter
  - jupyterlab
  - notebook
  - ipykernel
  - kaggle
  - numpy
  - networkx
  - python-dotenv
  - pandas
  - tqdm
  - kaggle
  - matplotlib
  - seaborn
  - plotly
  - squarify
  - scikit-learn
  - scipy
  - xgboost
  - pip
  - pip:
    - neo4j
    - neo4j-viz
    - playwright
